name: Build and Deploy

on:
  push:
    branches:
      - master
      - main
      - g-phone
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build 🔧
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm install
          npx webpack --config webpack.config.js --mode=production --devtool=false

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist